### ISSUE TITLE
essageListenerContainer$ListenerConsumer : Consumer exception

### ISSUE THREAD

**Issue by Bha91** [lokeshgupta1981/Kafka-Tutorials#2]
I got this error: 
`java.lang.IllegalStateException: This error handler cannot process 'SerializationException's directly; please consider configuring an 'ErrorHandlingDeserializer' in the value and/or key deserializer`
solved by commenting these lines in KafkaConsumerService
`    @KafkaListener(topics = AppConstants.TOPIC_NAME_TEST, groupId = AppConstants.GROUP_ID)
    public void consume(String message) {
        logger.info(String.format("Message recieved -> %s", message));}`

**Comment by lokeshgupta1981** [comment]
Thanks for sharing
